### PR TITLE
Fix comment on ERC777._beforeTokenTransfer

### PR DESCRIPTION
**Pull request by clayrab**
Simple comment cleanup

### CODE REVIEW

**Review by wkoff25 — COMMENTED** [review]
Fuck you

**Review by wkoff25 — COMMENTED** [review]
contracts/token/ERC777/ERC777.sol

**Comment by clayrab** [comment]
I was writing tests and wanted to make sure I had full coverage over all public functions which would call _beforeTokenTransfer(). Noticed this was missing and thought I might as well push the change up...

**Review by frangio — APPROVED** [review]
Thanks @clayrab. Note that our ERC777 implementation has now been deprecated (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4066), but for posterity I think it's good to fix this in the documentation.

**Pull request merged**
