### PR TITLE
Functions in SafeMath contract overloaded to accept custom error messages

### LINKED ISSUE #1827: Custom error messages as a third parameter to SafeMath functions
**🧐 Motivation**
It would be nice to have an option to add custom error message as a 3rd parameter to SafeMath contract functions.

**📝 Details**
One such example where it would be convenient is this:
`uint256 finalFund = funds[msg.sender].sub(amount, "No enough funds!");`

### PR DESCRIPTION
**Pull request by elch-yan**
Fixes #1827 
Overloaded counterparts of the existing functions created, and original functions calls redirected to them.

### CODE REVIEW

**Comment by nventuro** [comment]
Great work @elch-yan, thanks! Do you think you could also tackle the following?

1. Add an entry to the `CHANGELOG` file with this new feature
2. Add some of these custom checks to relevant contracts, e.g. `ERC20._transfer`, with a custom error message.

Regarding scope, I'm not sure how useful the overloads for `add`, `mul` `div` and `mod` are, since those are often used to check for actual arithmetic errors (overflows or division by zero) as opposed to e.g. sufficient balance. Perhaps we should limit this to `sub`? @frangio

**Comment by elch-yan** [comment]
Thank you @nventuro. Sure I'll update `CHANGELOG` and will add relevant checks to `ERC20._transfer`.
I was also been thinking about usefulness of this for the remaining 4 methods, and I guess that it might be somewhat useful for `div` and `mod` for 0 checks (spliting funds for example), but guess you're right about `mul` and `add`.

**Comment by nventuro** [comment]
>and I guess that it might be somewhat useful for div and mod for 0 checks (spliting funds for example)

Ohh, interesting! There are some examples of this in `PaymentSplitter`, `TokenVesting` and `IncreasingTimeCrowdsale`.

**Comment by elch-yan** [comment]
@nventuro I've made an entry in CHANGELOG, did some modifications in token contracts and related tests, regarding custom errors.
I looked at `PaymentSplitter`, `TokenVesting` and `IncreasingTimeCrowdsale` and I guess that in their case divisor can never become a 0.
I'd be happy to hear your opinion regarding my changes and about whether or not you'd like me to keep overloads for `SafeMath` functions other than `sub`.

**Comment by frangio** [comment]
I think we should only add those that we currently need, which seem to be `sub`, `div` and `mod`, from what @nventuro said.

**Comment by elch-yan** [comment]
All done!

**Comment by frangio** [comment]
Thanks @elch-yan!

One last thing: we would like to change the new error messages slightly to make them more aligned with the rest of the library. Could you apply the following changes?

- "transfer of tokens exceeding allowance" → "transfer amount exceeds allowance"
- "transfer of tokens exceeding balance" → "transfer amount exceeds balance"/"transfer amount exceeds supply" (depending whether the variable in the operation is the total supply)
- "decrease of higher allowance than granted" → "decreased allowance below zero"

Those which say "transfer" also apply to "burn".

**Pull request merged**
