### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by ernestognw**
Remove unused imports after changes for 5.0

### CODE REVIEW

**Comment by frangio** [comment]
Not sure why this caused tests to fail but it may be related to the custom error heuristics. See https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4437.

**Review by Amxx — DISMISSED** [review]

**Comment by ernestognw** [comment]
Seems like after transpilation, the tests are interpreting the errors as returndata. An example

```
AssertionError: Could not parse as custom error. VM Exception while processing transaction: reverted with an unrecognized custom error (return data: 0xd7e6bcf8)
```

Where `0xd7e6bcf8` is also `bytes4(keccak256('NotInitializing()'))`, confirming @frangio's theory with Hardhat's heuristics. I'm still confused why this happens after transpilation and not in the vanilla repo.

**Comment by ernestognw** [comment]
Seems like importing `Address.sol` in `Initializable` just makes it work.

**Comment by frangio** [comment]
Update: The issue was caused by https://github.com/NomicFoundation/hardhat/issues/4123! Cleaning vanilla artifacts after transpilation fixed it.

**Review by Amxx — APPROVED** [review]

**Pull request merged**
