### PR TITLE
Make IERC721 contracts interfaces instead

### PR DESCRIPTION
**Pull request by nventuro**
Fixes https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1679

I bumped the minimum required compiler for those files to Solidity v0.6.2, which [added the ability for interfaces to inherit from other interfaces](https://github.com/ethereum/solidity/releases/tag/v0.6.2).

### CODE REVIEW

**Comment by frangio** [comment]
Do we want to keep the inheritance? I think we have to keep an eye on https://github.com/ethereum/solidity/issues/7856. If ERC165 is integrated into the compiler we want to be able to use it, and it's being discussed whether inherited functions should be included in the calculated interface id.

**Comment by nventuro** [comment]
Yes, I think the inheritance is correct, and it looks like the Solidity team is considering our input there, so I don't foresee issues on that end.

**Comment by frangio** [comment]
I asked for information on the current direction just to be sure.

**Comment by nventuro** [comment]
I'll merge this to move the rc forward, though I don't expect for us to run into issues with the compiler.

**Comment by KaiRo-at** [comment]
You forgot IERC721Receiver. I filed #2217 for that. :)

**Pull request merged**
