### PR TITLE
Improve grammar in transfer error messages

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by frangio** [comment]
Thanks @lexmag. A bit reluctant on this one because it increases the size of the string and thus increases deployment costs. What would you say if we change "nor" to "or"?

**Comment by frangio** [comment]
The tests need to be updated to match the new revert reason, is this something you can do?

**Comment by lexmag** [comment]
The tests are updated. Also, fixed more occurrences of that wording.

**Review by frangio — APPROVED** [review]
Thank you!

**Pull request merged**
