### PR TITLE
Fix doc MyGovernor example doesn't compile

### LINKED ISSUE #4278: Fix docs snippets that don't compile
Consider updating the MyGovernor snippet on:
https://docs.openzeppelin.com/contracts/4.x/governance

The snippet is missing some mandatory function overrides.

### PR DESCRIPTION
**Pull request by qiweiii**
Fixes #4278  

- Put code snippet in [contracts/mocks/docs](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/mocks/docs) so it can be checked for compilation errors.
- Added `cancel` function that is missing
```solidity
function cancel(
    address[] memory targets,
    uint256[] memory values,
    bytes[] memory calldatas,
    bytes32 descriptionHash
) public override(Governor, GovernorCompatibilityBravo, IGovernor) returns (uint256) {
    return super.cancel(targets, values, calldatas, descriptionHash);
}
```

#### PR Checklist

- [x] Tests
- [x] Documentation
- [ ] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by frangio** [comment]
Thank you @qiweiii! Would you mind doing the same for the other Solidity contracts in `governance.adoc`?

**Comment by qiweiii** [comment]
Yea, happy to do it

**Comment by qiweiii** [comment]
@frangio Just added other solidity contract example, but I have a few concerns:
1. example contract naming could be confusing in future if move more example under `contracts/mocks/docs`, for example, there would be many `MyToken` in docs, instead of naming them `MyToken1`, `MyToken2`, do you think specific name like `MyTokenGovernance` could be better?
2. example code format is changed by solidity code formatter, after putting them in `.sol` file
```solidity
function _mint(address to, uint256 amount)
        internal
        override(ERC20, ERC20Votes)
    {
        super._mint(to, amount);
    }
```

is changed to 

```solidity
function _mint(address to, uint256 amount) internal override(ERC20, ERC20Votes) {
    super._mint(to, amount);
}
```

making the line a bit longer, user will need to scroll in order to read, is this acceptable?

**Comment by frangio** [comment]
1. Perhaps we can put them under `mocks/docs/governance/` to disambiguate that they are for the governance article. `MyTokenGovernance` is not necessary then. But it would still make sense to have different names that refer to the specific thing the example is showcasing.
2. Oh, this is not ideal but I don't know how to fix it so for now let's just accept what the formatter wants.

**Comment by frangio** [comment]
I realized `mocks/docs/governance/` would not have worked with one of our scripts so I pushed a commit to fix that.

**Comment by qiweiii** [comment]
> we can put them under mocks/docs/governance/ to disambiguate that they are for the governance article.

Good idea! 
I have put them under `/governance`, do you think the new contract names are good?

**Comment by qiweiii** [comment]
test-upgradable failed:
```
<--- Last few GCs --->

[1930:0x4e72540]  1644838 ms: Scavenge (reduce) 4063.6 (4098.7) -> 4062.7 (4098.7) MB, 8.4 / 0.0 ms  (average mu = 0.369, current mu = 0.359) allocation failure 
[1930:0x4e72540]  1644943 ms: Scavenge (reduce) 4063.6 (4095.7) -> 4062.7 (4096.7) MB, 18.3 / 0.0 ms  (average mu = 0.369, current mu = 0.359) allocation failure 
[1930:0x4e72540]  1645059 ms: Scavenge (reduce) 4063.7 (4095.7) -> 4062.7 (4096.7) MB, 11.3 / 0.0 ms  (average mu = 0.369, current mu = 0.359) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

do we need to increase the `--max_old_space_size`?

```diff
# .github/workflows/checks.yml
- NODE_OPTIONS: --max_old_space_size=4096
+ NODE_OPTIONS: --max_old_space_size=5120
```

**Comment by frangio** [comment]
I've retargeted the branch to `release-v4.9` and rebased on top of that because there are some new changes in `master` that affect this and we will want to update separately. I will open a separate PR to include the changes in `master`.

Thank you so much!

**Review by frangio — APPROVED** [review]

**Comment by Amxx** [comment]
This PR includes some changes to ERC721Consecutive (the offset part). I'm not sure its intentional. I also don't think it should be the case.

**Comment by frangio** [comment]
My bad, happened when I rebased... Will fix later.

**Review by frangio — APPROVED** [review]

**Pull request merged**
