### PR TITLE
Keep track of historical quorum values

### PR DESCRIPTION
**Pull request by Amxx**
Checkpointing quorum is necessary to avoid quorum changes making old, failed because of quorum, proposals suddenly successful.

#### PR Checklist

- [x] Tests
- [ ] Changelog entry

### CODE REVIEW

**Review by frangio — DISMISSED** [review]

**Comment by frangio** [comment]
Waiting until next week to discuss an alternative fix.

**Comment by frangio** [comment]
The issue with this PR is that it increases the cost of voting when the PreventLateQuorum module is used. It seems like this can be fixed by first checking if the latest checkpoint is the one we're looking for (in `quorumNumerator(uint blockNumber)`) and in that case avoid the binary search.

**Comment by Amxx** [comment]
I've implemented an optimistic lookup, that skips the binary search if the checkpoint we are looking for is the last one. However that only concerns `quorumNumerator(uint256)`. This function is mostly called through 

```
function quorum(uint256 blockNumber) public view virtual override returns (uint256) {
    return (token.getPastTotalSupply(blockNumber) * quorumNumerator(blockNumber)) / quorumDenominator();
}
```

The `token.getPastTotalSupply(blockNumber)` call will not be optimized the same way

**Comment by Amxx** [comment]
Not, the parts not covered are mechanism used in cases of migration.

**Review by frangio — APPROVED** [review]

**Pull request merged**
