### PR TITLE
Fix flaky timestamp tests 

### PR DESCRIPTION
**Pull request by frangio**
They are due to an how OpenZeppelin Test Helpers implements `time.increaseTo`. We should prefer Hardhat's own network helpers (eventually we should migrate the rest of the test suite).

I also included a small refactor of `.then` in the Governor helper.

Fixes #4045

### CODE REVIEW

**Review by Amxx — DISMISSED** [review]
Awesome !

**Comment by frangio** [comment]
The test suite is going a lot slower than before I think. But I don't think it's due to this PR.

**Comment by frangio** [comment]
Test suite took twice the time it usually takes. I'm disabling gas reporting to see if it helps.

**Comment by Amxx** [comment]
> Test suite took twice the time it usually takes. I'm disabling gas reporting to see if it helps.

gas report definitelly making all tests WAY slower

**Comment by frangio** [comment]
| Gas Reporter | OZ Helpers | Nomic Helpers |
|-|--|--|
| on | 20m | TBD |
| off | 10m | 22m |

**Comment by Amxx** [comment]
It made sens that #d79c2ecb6d31f82650fe71fef08364c208a4abea would fix the issue of flaky timestamps, but I'm not sure how we expect the current version of the PR to do anything since the behavior for timestamps in `helper/time.js` is no longer part of the diff.

**Comment by frangio** [comment]
@Amxx I'm just trying things out to debug the test time degradation.

**Pull request merged**
