### PR TITLE
Deduplicate code in `scripts/helpers` and `test/helpers/iterate`

### PR DESCRIPTION
**Pull request by Amxx**
#### PR Checklist

- [x] Tests
- [ ] Documentation
- [ ] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Review by ernestognw — APPROVED** [review]
I checked where the functions are used in the `scripts` folder and so far:

- `chunk`: Unused
- `product`: Unused
- `range`: In the SafeCast template
- `unique`: Unused
- `zip`: Unused
- `mapValues`: Unused
- `capitalize`: In multiple templates

Since these are used within automatic generation, these are already checked in the CI so I'm approving.

However, I wonder if it makes sense to keep the helpers in where they're used the most (i.e `tests/`)

**Comment by ernestognw** [comment]
CI failing due to #4896. Rerunning

**Comment by Amxx** [comment]
> However, I wonder if it makes sense to keep the helpers in where they're used the most (i.e `tests/`)

I considered keeping all that code in `test/helpers/iterate.js` and have the generation script point to that. It felt strange to have "production" scripts rely on testing code... but at the same time, `iterate.js` sounds like a better description of what the file contains.

**Comment by Amxx** [comment]
[For the record, the "chunk" helpers was used in Forta's early days.](https://github.com/forta-network/forta-contracts/blob/master/scripts/deployments/deploy-token.js#L126-L149)

We wanted to relay a lot of transaction trough multicall, but not all at once (we did that in blocks of 16 so that we benefit from multicall while limiting the size of the multicall transaction)

**Comment by ernestognw** [comment]
> It felt strange to have "production" scripts rely on testing code...

Right, that feels weird. I think this is better anyway since we don't ship those scripts. And they're checked in the CI.

**Review by ernestognw — APPROVED** [review]
LGTM

**Pull request merged**
