### PR TITLE
Imrove `BitMaps` documentation

### PR DESCRIPTION
**Pull request by sebastiantf**
~Fixes typo in `BitMaps` docs~

Improves `BitMaps` documentation

#### PR Checklist

- [ ] Tests
- [x] Documentation
- [ ] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by ernestognw** [comment]
Hey @sebastiantf. Perhaps this is a good opportunity to enhance the docstrings in this contract. 

What the original text referring to is that the BitMap locates each boolean in contiguous storage word locations. For example, each `uint256` key points to 256 bits (32-byte word), so the booleans for keys 1, 2 and 3 will be located contiguously in the same storage location.

I'd suggest rephrasing the text to better reflect this before merging.

**Comment by sebastiantf** [comment]
Sounds good. I'll push an update to the text in some time

**Comment by sebastiantf** [comment]
@ernestognw Pushed a change. Please have a look. Cannot seem to request any reviewers

**Review by Amxx — APPROVED** [review]

**Review by frangio — APPROVED** [review]
Great change. LGTM.

**Review by ernestognw — APPROVED** [review]
LGTM, thanks!

**Review by ernestognw — APPROVED** [review]
Reapproving because the linter check was failing

**Pull request merged**
