### PR TITLE
SafeERC20 safeBalanceOf and safeAllowance for proxy-based tokens

### PR DESCRIPTION
**Pull request by k06a**
~`DELEGATECALL` inside `STATICCALL` produces a `REVERT`, so I just replaced `STATICALL` with `CALL`.~

~This PR solves problem:~
- ~Calling view methonds of proxy-based token smart contract from **Solidity**~

~Should also think how to fix problem:~
- ~Calling view methonds of proxy-based token smart contract from **Web3**~

### CODE REVIEW

**Comment by k06a** [comment]
I think we also need to introduce `SafeERC20Detailed` with the same helpers.

**Comment by nventuro** [comment]
Hello @k06a, thanks for contributing!

This initially made me panic a bit, but after reading the [`STATICCALL` EIP](https://eips.ethereum.org/EIPS/eip-214) I found no references to `DELEGATECALL`. I also did some testing locally and went through the implementation in [ethereumjs-vm](https://github.com/ethereumjs/ethereumjs-vm), and everything seems to be fine.

Could you expand a bit more on the issue you're facing, and how to trigger it? Thanks!

**Comment by k06a** [comment]
Try to call `balanceOf` of `cETH`: https://etherscan.io/token/0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5

**Comment by k06a** [comment]
https://etherscan.io/tx/0xae737b195efcc9f39103be5e1672513b46f388d82905f266ff9d3899941f571b:
image
```
Decoded call tree:
* [1] 0x0f0e98de(0x000000000000000000000000d94916c3a62a4206273a2574bb6f6f951c8d3882000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000900000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a232603590000000000000000000000009f8f72aa9304c8b593d555f12ef6589cc3a579a200000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a2326035900000000000000000000000057ab1e02fee23774580c119740129eac7081e9d3000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359000000000000000000000000744d70fdbe2ba4cf95131626614a1763df805b9e0000000000000000000000000000000000000000000000000000000000000009000000000000000000000000f37faaefb79518086da310eb984859b0a35bc820000000000000000000000000f37faaefb79518086da310eb984859b0a35bc8200000000000000000000000003fda67f7583380e67ef93072294a7fac882fd7e70000000000000000000000003fda67f7583380e67ef93072294a7fac882fd7e70000000000000000000000003a306a399085f3460bbcb5b77015ab33806a10d5000000000000000000000000a1ecdcca26150cf69090280ee2ee32347c238c7b000000000000000000000000e2338ad2d71e06b002fc31b79a85007d3fd81f3e000000000000000000000000391a12ab01e6a4f8c3d2e7eca8af931bec704f150000000000000000000000001aec8f11a7e78dc22477e91ed924fab46e3a88fd) { to: 0xec15fa2e42aa485305d688ea79013693e3349eca }
    [2] allowance((address)(0xd94916c3a62a4206273a2574bb6f6f951c8d3882),(address)(0xf37faaefb79518086da310eb984859b0a35bc820)):0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
    [3] decimals():0x12 { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
    [4] symbol():0x4441490000000000000000000000000000000000000000000000000000000000 { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
    [5] allowance((address)(0xd94916c3a62a4206273a2574bb6f6f951c8d3882),(address)(0xf37faaefb79518086da310eb984859b0a35bc820)):0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff { to: 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2 }
    [6] decimals():0x12 { to: 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2 }
    [7] symbol():0x4d4b520000000000000000000000000000000000000000000000000000000000 { to: 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2 }
    [8] allowance((address)(0xd94916c3a62a4206273a2574bb6f6f951c8d3882),(address)(0x3fda67f7583380e67ef93072294a7fac882fd7e7)):0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
    [9] decimals():0x12 { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
    [10] symbol():0x4441490000000000000000000000000000000000000000000000000000000000 { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
    [11] allowance((address)(0xd94916c3a62a4206273a2574bb6f6f951c8d3882),(address)(0x3fda67f7583380e67ef93072294a7fac882fd7e7)):0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff { to: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 }
    [12] decimals():0x12 { to: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 }
    [13] symbol():0x2000000000000000000000000000000000000000000000000000000000000000045745544800000000000000000000000000000000000000000000000000000000 { to: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 }
    [14] allowance((address)(0xd94916c3a62a4206273a2574bb6f6f951c8d3882),(address)(0x3a306a399085f3460bbcb5b77015ab33806a10d5)):0x800000000000016c889a28c160ce0422bb9138ff1d4e482717c1215d675e0000 { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
    [15] decimals():0x12 { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
    [16] symbol():0x4441490000000000000000000000000000000000000000000000000000000000 { to: 0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359 }
  * [17] allowance((address)(0xd94916c3a62a4206273a2574bb6f6f951c8d3882),(address)(0xa1ecdcca26150cf69090280ee2ee32347c238c7b)) { to: 0x57ab1e02fee23774580c119740129eac7081e9d3 }
      [18] setMessageSender((address)(0xec15fa2e42aa485305d688ea79013693e3349eca)) { to: 0x0cbe2df57ca9191b64a7af3baa3f946fa7df2f25 }
```

**Comment by k06a** [comment]
@nventuro just checked. It seems I was wrong about `DELEGATECALL`, but what do you think of `SSTORE`s inside of balanceOf for some tokens?

**Comment by nventuro** [comment]
From the [EIP](https://eips.ethereum.org/EIPS/eip-20#specification), `balanceOf` is a `view` function, so any `SSTORE` opcodes in its implementation would make it non-`view` and therefore non-compliant. Can you share examples of such behavior?

**Comment by k06a** [comment]
@nventuro this token have `SSTORE` inside `DELEGATECALL`: https://etherscan.io/address/0x57ab1e02fee23774580c119740129eac7081e9d3

**Comment by frangio** [comment]
@k06a Note that `sstore` inside `delegatecall` is not a problem. The only problem is `sstore` in `staticcall` context. Is this happening in the contract you mention?

**Comment by k06a** [comment]
@frangio I met it in at least 2 tokens.

**Comment by frangio** [comment]
Solidity semantics say that `view` functions are `staticcall`-able, and I don't think we should diverge from that, given that the ERC20 spec says `balanceOf` is `view`. This is complicated, though, because this was not explicitly the semantics of `constant` functions when the ERC20 spec was written. I still think that we should stick to `staticcall` because it's safer.

The proposed `safeBalanceOf` function actually seems to be less safe than bare `balanceOf`, because of the possibility of reentrancy.

**Comment by k06a** [comment]
@frangio I agree, sorry for disturbing you guys.

**Pull request closed without merging**
