### PR TITLE
Add functionStaticCall and functionDelegateCall methods to Address library

### PR DESCRIPTION
**Pull request by k06a**
Consider having `functionStaticCall` and `functionDelegateCall` methods in `Address` library.

### CODE REVIEW

**Comment by frangio** [comment]
@k06a Do you have any comments on the topic of avoiding the repeated code?

**Comment by k06a** [comment]
@frangio we could aggregate only `call` and `delegatecall` since they are both non-view methods :(

**Comment by frangio** [comment]
Ah that's a good point.

I think we should be able to put the if conditional inside a separate private function that can be reused though. Could you try that out in this PR?

**Comment by k06a** [comment]
@frangio did, can't make it work with function pointers because of `view` modifiers.

**Comment by frangio** [comment]
@k06a This PR is great but you seem to have deleted the natspec documentation. :smile: Let me know if you can add it back, along with similar docs for the new functions, or if you want me to take care of it.

Thank you!

**Comment by k06a** [comment]
@frangio sorry about this, could someone help to restore it? You could simply push your own commits to my branch since I opened PR - it is allowed by github default settings :)

**Comment by frangio** [comment]
No problem, I'll take care of it.

**Pull request merged**
