### PR TITLE
Add getter for number of releasable tokens in VestingWallet

### PR DESCRIPTION
**Pull request by Amxx**
Similar to #3350, but for the VestingWallet

#### PR Checklist

- [x] Tests
- [x] Changelog entry

### CODE REVIEW

**Review by frangio — APPROVED** [review]

**Review by frangio — CHANGES_REQUESTED** [review]
Needs tests.

**Comment by Amxx** [comment]
Its already covered by the fact "release" reads it ... but sure

**Comment by trastvolt** [comment]
Amxx:feature/vesting/releasable

**Comment by trastvolt** [comment]
Amxx:feature/vesting/releasable

**Review by frangio — APPROVED** [review]
LGTM

**Review by frangio — APPROVED** [review]

**Pull request merged**
