### PR TITLE
Remove redundant else and improve readability

### PR DESCRIPTION
**Pull request by MrClottom**
Small code change to improve readability. This PR does not change any functionality.

### CODE REVIEW

**Comment by MrClottom** [comment]
The tests that fail are apparently failing because of a timeout, don't know how my change could cause that, does anyone know why this could be happening?

**Comment by frangio** [comment]
Sorry for that timeout @MrClottom. It's a flakiness in our test suite that we haven't been able to track down yet.

Using early returns versus exlicit else branches is a matter of style, and we prefer the style that we're currently using, so I'm going to reject these changes. But thank you for the suggestion and the PR!

**Comment by MrClottom** [comment]
What if the explicit `else` after the return were to be kept but the `if (condition) else revert` were replaced with a `require` as suggested?

**Comment by frangio** [comment]
No, I'm sorry.

**Comment by MrClottom** [comment]
@frangio Ok but why? Isn't that the whole point of the revert function? The inner if else just hurts readability, is there some additional functionality that I'm missing? I can open a separate issue with the only one change if it's preferred.

**Pull request closed without merging**
