### PR TITLE
Bump minimum pragma version to `0.8.19`

### PR DESCRIPTION
**Pull request by ernestognw**
#### PR Checklist

Bump the minimum pragma version to 0.8.19

- [x] Tests
- [x] Documentation
- [ ] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by ernestognw** [comment]
Do we need a changeset for this? I didn't find any other similar entry in the CHANGELOG

**Comment by frangio** [comment]
Yes this needs a changeset.

**Comment by ernestognw** [comment]
> Yes this needs a changeset.

Added, thanks!

**Review by frangio — APPROVED** [review]
LGTM

**Review by Amxx — APPROVED** [review]
LGTM

**Comment by ernestognw** [comment]
Gas comparison is failing because bumping the pragma version makes the comparison incompatible but is intended. Tests are passing so I'm manually merging.

**Pull request merged**
