### PR TITLE
Add Strings.toHex()

### PR DESCRIPTION
**Pull request by k06a**
Proposing converting `uint256`, `address`, `bool`, and `bytes32` to a hexadecimal string.

Gonna add tests and docs in case of the PR will be considered as useful :)

### CODE REVIEW

**Comment by k06a** [comment]
I use this mostly for debugging, and believe this is more compact and efficient way to present numbers. To debug sometimes I use:
```solidity
revert(toHex(value));
```

**Comment by frangio** [comment]
I think this can be useful but we would need tests!

**Review by TomasFlow — APPROVED** [review]

**Review by TomasFlow — APPROVED** [review]

**Comment by k06a** [comment]
@frangio do you think we also need non-padded version for `uint256`? To print `123` as `0x7B` instead of `0x000000000000000000000000000000000000000000000000000000000000007B`.

**Comment by frangio** [comment]
@k06a Which version is most useful in your experience? I would prefer to add a single version.

**Comment by k06a** [comment]
@frangio proposed implementation is very compact, I would prefer to keep it:

image

**Comment by frangio** [comment]
If we were to implement trimming of zero-padding I would do it in `toHex(bytes)`, so `toHex(uint256)` etc. would remain the same.

`toHex(bytes)` is already not so compact, but I don't know how many lines would have to be added.

**Comment by frangio** [comment]
Closing this in favor of #2504

**Pull request closed without merging**
