### PR TITLE
Addition of Array Sorting functions

### PR DESCRIPTION
**Pull request by fps8k**
## Open-Zeppelin Feature.

Addition of Array Sorting functions.

## Environment used.

- Compiler version: 0.8.7
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix
- Operating system: Windows

## Array Sorting functions.

After going through the [Array.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Arrays.sol), it felt quite necessary that a function that would sort arrays in ascending or descending order would be necessary.

That is what this pull request seeks to add.

I would be glad, if the Open-Zeppelin team reviewed, corrected and accepted my code.

# How can this feature help?.

Sorting arrays directly from the smart contract when necessary, especially when an array (which might seem unordered) is wanted to be passed to the findUpperBound function.

###

Thank you.

Anthony (fps).

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @fps8k 

There are many things to say here:
- your implementation is a selection sort, which is known to be 0(n²) ... this is bad. If we were to ever implement that, we should go with an in-place quicksort. [I wrote a solidity implementation of quicksort a while back](https://gist.github.com/Amxx/d3a99fcb79abbe3c76a2f2a5773b3815).
- you read from storage, which makes everything super expensive, particularly in the context of a selection sort where there are 0(n²) reads.
- empty arrays are already sorted, reverting if the array is empty makes no sense.

More importantly, I don't think we should provide a sorting function at all. Sorting is expensive, and I would argue devs should design their contract so that sorting is not needed.

If sorting was to be implemented on-chain, it should be done in a way that minimizes the storage change when inserting/extracting elements. So probably some tree (red-black would be my first guess). Arrays are a terrible choice. Lastly, if you really want to sort an array, do it using an O(n log(n)) algorithm, and in memory (not storage !!!)

We always ask contributors to open issues before creating a PR. Doing so would have saved you time and effort.

**Comment by Amxx** [comment]
From your own metrics, sorting an array of 8 elements cost >150k gas. That is 18k gas per element, and its going to grow quadratically. 

That is:
16 elements: ~600k gas
32 elements: ~2.4m gas
64 elements: ~9.6m gas

I hope you realize this is not something we can release. People will build contracts on top of that, reach 120~150 entries onchain ... and then running the sorting algorithm would fit an entire block out of gas ... which will block all operation that rely on this sorting.

**Comment by fps8k** [comment]
Thank you for your reviews. I will try to be better.

**Comment by Amxx** [comment]
Before submitting PR, please open issues so we can discuss the overall design first.

**Comment by Amxx** [comment]
Related issue: #3410

**Comment by fps8k** [comment]
I will, next time.

**Pull request closed without merging**
