### PR TITLE
Use unchecked in MerkleProof.processMultiProof

### PR DESCRIPTION
**Pull request by pcaversaccio**
As title. The array index cannot become negative by design (i.e. cannot underflow) so I would suggest using unchecked arithmetic for the `totalHashes - 1` expression. Also, this PR fixes a small typo. Since it's a refactor PR, I do not include a `CHANGELOG` entry.

### CODE REVIEW

**Review by frangio — APPROVED** [review]
I reduced the scope of `unchecked` to only what is needed. Did not include a comment to explain `unchecked` because the reason is found in the immediately prior line.

**Comment by pcaversaccio** [comment]
Makes sense, thx @frangio.

**Review by ernestognw — APPROVED** [review]
Thanks for the catch @pcaversaccio

**Comment by frangio** [comment]
@pcaversaccio You might be the first to mint this GitPOAP. :eyes:

**Comment by pcaversaccio** [comment]
> @pcaversaccio You might be the first to mint this GitPOAP. 👀

oh nice :-D - actually just found out that am eligible for two others as well :) 

image

**Pull request merged**
