### PR TITLE
Improve error messages for ERC721 and 1155

### LINKED ISSUE #3120: Improve clarity of error messages in functions checking token ownership
**🧐 Motivation**
Good morning folks. I feel this somewhat walks the line between feature and bug.

While extending some `.*transfer()` functionality in the OpenZeppelin contracts (thank you for providing them!) I found some of my tests failing due to an error reading:

```
ERC721: transfer caller is not owner nor approved
```

As a newcomer, most of the terminology of ownership in documentation and in the "higher level" contracts refers to the contract owner - with frequently used modifiers like `onlyOwner` and the `Ownable` contract reinforcing this. I spent quite some verifying that the test was indeed making calls with the owner's signature, and that signature matches the `.owner()` in the instance of the contract under test. 

After delving in a little more I found that the term "owner", in this context, refers to the _token_ owner. 

(A more dramatic reading of this experience as at the bottom for those interested in such things)

**📝 Details**
A small amount of clarification may go a long way to saving others the journey I went on myself, for example extending the error message to

```
ERC721: transfer caller is not *token* owner nor approved
```

I have a PR ready with this, and for all similar instances of such messages. Thank you for your consideration.

**Dramatic Reading**
>"But I am the owner", I whinge at the test suite, exhausted. In red, emblazoned in the flickering terminal: "'ERC721: transfer caller is not owner nor approved'" stands its ground - repeatedly unconvinced of my ownership. I checksum, and I verify. The messages are signed with poise, grace, and cryptographic correctness. The deployer is requesting the transfer. The very deployer that is also the current owner of this fine establishment.
So I dig. I fear I'll dig too greedily and too deep, and awaken something in the darkness.
"Ah." I sigh. Owner can mean owner of the contract, but this "owner" refers to a check of owner of the token.
So let this fable guide you all - don't reuse curt terminology for something that is already overloaded. All this could have been avoided with a simple
"ERC721: transfer caller is not *token* owner nor approved".

### PR DESCRIPTION
**Pull request by kanedaaaa**
Fixes #3120 

As discussed in the issue, the ERC721 approve error message was misleading. 

All tho, we can say the same thing on a very similar error message:
`"ERC1155: the caller is not owner nor approved"` or `"ERC721: approve caller is not owner nor approved for all"`

I didn't modify this one since the first error message fix was accepted because it's more meaningful and shorter than the previous one, which won't apply in this. And also, there is an open [PR](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3121f) that fixes the same issue. But still, would be nice if I could add `token` in mentioned messages.

P.S The PR mentioned above also goes against my logic (removing the "transfer" keyword in my version) so definitely check it.

- [x] Tests
- [ ] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Review by Amxx — DISMISSED** [review]
LGTM

**Comment by Amxx** [comment]
Wait, you are missing ERC1155Burnable

**Comment by kanedaaaa** [comment]
@Amxx Refer to what i said above. These messages aren't consistent. Thus, I had to modify only ones that contained "transfer" before "caller". I pointed out that there is another PR that completely modified every single "token owner" error message.

**Comment by Amxx** [comment]
In ERC1155 there is `ERC1155: caller is not owner nor approved`. IMO the confusion with a possible contract owner also exists

**Comment by frangio** [comment]
This PR is now increasing the length of revert reasons, which we initially thought would just be shortened in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3120#issuecomment-1059982675, so it now needs some more analysis to see how this is affecting bytecode size before we agree to merge.

**Comment by kanedaaaa** [comment]
Yes, i think this convo went from making shorter to making more clear what revert reason says. All tho, i have this idea regarding to error messages:

What if there were error codes, rather than full revert message, such as:

```ERC1155: ERR_001``` - Then, we can write down in docs what this `ERR_001` means, with more explanation and examples. 

Shortens the bytecode, and it's more organised in general. But anyways, custom error messages are on the way and we might as well wait for it to be fully implementable. As i know there is still no way to trigger them with `require()`

**Comment by kanedaaaa** [comment]
Yes, i think there was bit of misunderstanding here regarding to that. My first commit shortened the error messages, so we can just go back there since other changes that made messages longer is in second commit. 

BTW, i was just thinking and since we are discussing same thing: what if there were error codes, rather than full revert message, such as:

ERC1155: ERR_001 - Then, we can write down in docs what this ERR_001 means, with more explanation and examples.

Good example from PancakeSwap: https://docs.pancakeswap.finance/help/troubleshooting

Shortens the bytecode, and it's more organised in general. But anyways, custom error messages are on the way and we might as well wait for it to be fully implementable. As i know there is still no way to trigger them with require()

**Comment by frangio** [comment]
We're catching up on pending PRs. Sorry for the delay @kanedaaaa.

Following up on my last point, I realized that the change is still net positive because in this PR you are unifying what were different revert reasons into the same revert reason and this gets optimized by the compiler so the constant is present only once in the code.

We used to have the goal to have different revert reasons for every different error condition so that the source of an error would be easy to identify, but I don't think this is a strong argument anymore because tooling has evolved and e.g. Hardhat can show the real source of an error.

**Review by frangio — APPROVED** [review]
Thank you!

**Review by frangio — APPROVED** [review]

**Pull request merged**
