### PR TITLE
Gas optimization for tryMul function

### PR DESCRIPTION
**Pull request by SovaSlava**
Gas optimization for tryMul function in Math library. 
Removed local variable 'c'. 
Gas difference 4 wei.

#### PR Checklist

- [X] Tests
- [X] Documentation
- [X] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by ernestognw** [comment]
Hi @SovaSlava, sorry for the late response.

I did some tests and yeah, seems to save around ~5 gas units:

```
# forge snapshot --match-test testTryMul -vvvv --use 0.8.24
MathModifiedTest:testTryMul(uint256,uint256) (runs: 256, μ: 485, ~: 486)
MathTest:testTryMul(uint256,uint256) (runs: 256, μ: 484, ~: 481)
```

However, when run via-ir, the results are the same, so this is the kind of optimization that don't impact in production versions (if compiled properly):

```
forge snapshot --match-test testTryMul -vvvv --use 0.8.24
MathModifiedTest:testTryMul(uint256,uint256) (runs: 256, μ: 333, ~: 333)
MathTest:testTryMul(uint256,uint256) (runs: 256, μ: 333, ~: 333)
```

I would be fine merging this though.

**Comment by Amxx** [comment]
I'm wondering if that function should not be rewritten as branchless

```solidity
    function tryMul(uint256 a, uint256 b) public pure returns (bool success, uint256 result) {
        unchecked
        { 
            success = a == 0 || ((a * b) / a == b);
            result = a * b * success.toUint();
        }
    }
```

**Comment by Amxx** [comment]
I tried replicating the result using

```solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.20;

import {Test, stdError} from "forge-std/Test.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";
import {SafeCast} from "@openzeppelin/contracts/utils/math/SafeCast.sol";

library Math2 {
    function tryMul(uint256 a, uint256 b) internal pure returns (bool success, uint256 result) {
        unchecked {
            if (a == 0) return (true, 0);
            if ((a*b)/a != b) return (false, 0);
            return (true, a*b);
        }
    }
}

library Math3 {
    using SafeCast for bool;

    function tryMul(uint256 a, uint256 b) internal pure returns (bool success, uint256 result) {
        unchecked {
            success = a == 0 || ((a * b) / a == b);
            result = a * b * success.toUint();
        }
    }
}

contract MathTry1 is Test {
    function testTryMult(uint256 a, uint256 b) public {
        Math.tryMul(a, b);
        assertTrue(true);
    }
}

contract MathTry2 is Test {
    function testTryMult(uint256 a, uint256 b) public {
        Math2.tryMul(a, b);
        assertTrue(true);
    }
}

contract MathTry3 is Test {
    function testTryMult(uint256 a, uint256 b) public {
        Math3.tryMul(a, b);
        assertTrue(true);
    }
}
```

I get:
Capture d’écran du 2024-04-22 10-36-52

To me it looks like the proposed change is the worst option, and that the branchless one is the best.
@ernestognw can you please verify ? What code did you use for benchmarking?

**Comment by ernestognw** [comment]
> I'm wondering if that function should not be rewritten as branchless
> 
> ```solidity
>     function tryMul(uint256 a, uint256 b) internal pure returns (bool success, uint256 result) {
>         unchecked { 
>             success = a == 0 || ((a * b) / a == b);
>             result = a * b * success.toUint();
>         }
>     }
> ```

I feel like this is on the edge of not being easily readable anymore.

In regards to your tests, these are the files I used: https://gist.github.com/ernestognw/c12bad17d13f3b4fea4293e27642e81c
I'm realizing I misinterpreted the numbers, this proposal is indeed more costly than the original, although there's still no difference when compiling via-ir.

Removing the approval given I don't see reasons to merge it anymore

**Pull request closed without merging**
