### PR TITLE
Fix deprecation warnings

### LINKED ISSUE #2146: Address.sol - Warning: Using ".value(...)" is deprecated. Use "{value: ...}" instead.
Compiling contract which uses Address.sol results in warning
```
$ npx oz compile
✓ Compiled contracts with solc 0.6.4 (commit.1dca32f3)
Compilation warnings:
@openzeppelin/contracts/utils/Address.sol:55:28: Warning: Using ".value(...)" is deprecated. Use "{value: ...}" instead.
        (bool success, ) = recipient.call.value(amount)("");
                           ^------------------^
```

**💻 Environment**

OpenZeppelin Contracts 3.0 (3.0.0-rc.0)
OpenZeppelin CLI 2.8 (2.8.0-rc.4)

**📝 Details**
Compiling with solc 0.6.4

**🔢 Code to reproduce bug**
Compile a contract using Address.sol
## AddressImpl.sol
```
pragma solidity ^0.6.0;

import "@openzeppelin/contracts/utils/Address.sol";

contract AddressImpl {
    function isContract(address account) external view returns (bool) {
        return Address.isContract(account);
    }

    function sendValue(address payable receiver, uint256 amount) external {
        Address.sendValue(receiver, amount);
    }

    // sendValue's tests require the contract to hold Ether
    receive () external payable { }
}
```
```
$ npx oz compile
✓ Compiled contracts with solc 0.6.4 (commit.1dca32f3)
Compilation warnings:
@openzeppelin/contracts/utils/Address.sol:55:28: Warning: Using ".value(...)" is deprecated. Use "{value: ...}" instead.
        (bool success, ) = recipient.call.value(amount)("");
                           ^------------------^
```

### PR DESCRIPTION
**Pull request by nventuro**
This removes the deprecation warnings emitted by the Solidity compiler starting on v0.6.4. Unfortunately, the new notation was only introduced on v0.6.2, so we're forced to bump the minimum compiler version for those contracts if we want to fix this.

The linter will fail due to this new syntax not being yet supported, I made a comment [on their v0.6 support issue](https://github.com/protofire/solhint/issues/170).

Closes #2146

### CODE REVIEW

**Comment by frangio** [comment]
I think it's fine to bump the pragma, it's not even a breaking change since there is no stable Contracts release yet. I would consider bumping the pragma for all our files to avoid breaking changes in the future.

**Comment by nventuro** [comment]
I'll postpone the decision on bumping until we're closer to releasing, in case similar requirements appear in other contracts.

Meanwhile, I'll hold off merging this until https://github.com/protofire/solhint/issues/170 is fixed.

**Comment by nventuro** [comment]
The latest release candidate of solhint is able to properly parse this!

See [this comment](https://github.com/protofire/solhint/issues/170#issuecomment-614281420) for why the new linter directive exists.

**Comment by frangio** [comment]
We should bump the compiler pragma for all files. Can you do that in this PR?

**Comment by nventuro** [comment]
Bump to what version? Each file states the minimum required compiler version to compile with no warnings.

**Comment by frangio** [comment]
I think we should bump at least to version 0.6.2 in case this piece of syntax shows up in any of the other files. And I would actually bump to a newer version, just in case there is some other feature that we may want to use in the future, so that we can do it without bumping the minimum required solc version which is technically a breaking change. There may not be any interesting features in the other solc versions though.

**Comment by nventuro** [comment]
I'd very much prefer to only specify the version the code actually requires, and not bump it unnecessarily. If a new version comes out with features we consider are useful and let us write better code, we'll use them, but I don't think we should force everyone to use the latest compiler version. See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1726.

**Comment by frangio** [comment]
Okay, I agree to keep the minimum required version. But note that part of the argument in that issue was that bumping the version regularly was breaking the builds of users. I was trying to say that if we update now rather than after 3.0, we will avoid those breaking changes in the future. In any case, many people are already using the release candidates so this would be an unnecessary breaking change already.

**Comment by nventuro** [comment]
If we were to bump after 3.0 then wouldn't it be due to a new unreleased compiler feature though?

**Comment by frangio** [comment]
It could be because we have to use the new syntax in this PR in new functionality in one of the existing contracts. Seems unlikely though.

**Pull request merged**
