### PR TITLE
Argument missing in approve method.

### PR DESCRIPTION
**Pull request by rahulct17**
the recipient argument was missing in the  approve message

Fixes #

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @rahulct17  and thank you for your PR.

Could you please explain what you are trying to fix? The approve function, as currently implemented, correspond to the [ERC20 standard](https://eips.ethereum.org/EIPS/eip-20). Furthermore, the parameter you are adding is unused.

**Comment by rahulct17** [comment]
When run in remix ide ...the approve function has some error showing it is
not an override function...

So when we pass the argument (address recipient) it runs without any errors

**Comment by Amxx** [comment]
The ERC20 interface is standard and should not be changed. It you have an issue using this contract in Remix, it would be much better to find the origine of the issue and fix it. Would you be able to provide a piece of code that, when put into remix, reproduces your issue ?

**Comment by rahulct17** [comment]
Please see the attachment

**Comment by frangio** [comment]
@rahulct17 We didn't receive an attachment here in the GitHub pull request.

If Remix is showing an error related to overrides, then there is something else wrong in your setup.

**Comment by rahulct17** [comment]
Please provide your email  address so I can explain you about the issue

**Comment by frangio** [comment]
For support please visit https://forum.openzeppelin.com and create a thread to discuss your issue.

**Pull request closed without merging**
