### PR TITLE
Remove String.sol library dependency in AccessControl.sol

### LINKED ISSUE #3615: AccessControl report bug: TypeError: Member "toHexString" not found or not visible after argument-dependent lookup in type(library Strings).
When I ran [AccessControl.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol), there is bug report:

```
TypeError: Member "toHexString" not found or not visible after argument-dependent lookup in type(library Strings).
```
**📝 Details**

There is a bug for `_checkRole()` function
```solidity
    function _checkRole(bytes32 role, address account) internal view virtual {
        if (!hasRole(role, account)) {
            revert(
                string(
                    abi.encodePacked(
                        "AccessControl: account ",
                        Strings.toHexString(account),
                        " is missing role ",
                        Strings.toHexString(uint256(role), 32)
                    )
                )
            );
        }
    }
```

The `toHexString` function in `String.sol` library is `internal`. I suggest removing the `String.sol` library import.

**🔢 Code to reproduce bug**

Run AccessControl.sol

### PR DESCRIPTION
**Pull request by AmazingAng**
Fixes #3615 

I removed `String.sol` library dependency in `AccessControl.sol`

- [ y] Tests
- [ y] Documentation
- [ y] Changelog entry

### CODE REVIEW

**Comment by Amxx** [comment]
One of your commit say

> There is a bug for `_checkRole()` function:
> 
> The `toHexString` function in `String.sol` library is internal. I removed the `String.sol` library import.

What the the bug? I'm not seeing it.

**Comment by trastvolt** [comment]
AmazingAng:master

**Comment by AmazingAng** [comment]
> One of your commit say
> 
> > There is a bug for `_checkRole()` function:
> > The `toHexString` function in `String.sol` library is internal. I removed the `String.sol` library import.
> 
> What the the bug? I'm not seeing it.

In [AcessControl](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol) :
```solidity
import "../utils/Strings.sol";


    function _checkRole(bytes32 role, address account) internal view virtual {
        if (!hasRole(role, account)) {
            revert(
                string(
                    abi.encodePacked(
                        "AccessControl: account ",
                        Strings.toHexString(account),
                        " is missing role ",
                        Strings.toHexString(uint256(role), 32)
                    )
                )
            );
        }
    }
```

And in `Strings.sol` library:
```solidity
    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
```

The `AccessMaster.sol` import "../utils/Strings.sol", and uses `Strings.toHexString()` function directly. But `Strings.toHexString()` is internal.

**Comment by Amxx** [comment]
You probably had an old version in Remix's cache.

**Pull request closed without merging**
