### PR TITLE
Update typehash string formatting

### PR DESCRIPTION
**Pull request by k06a**
Hope you'll like it, because this required to modify https://github.com/prettier-solidity/prettier-plugin-solidity/pull/575

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @k06a and thank you for yet another great proposal.

I didn't know that `keccak` includes an implicit `abi.encodePacked`/`bytes.concat`.

**Comment by k06a** [comment]
@Amxx this is called [Multi-line string literal](https://docs.soliditylang.org/en/v0.8.7/grammar.html?highlight=literal#a4.SolidityParser.stringLiteral). These three strings are identical in terms of compiled source code.
```
"Ballot(uint256 proposalId,uint8 support)"
```
```
"Ballot(" "uint256 proposalId," "uint8 support" ")"
```
```
"Ballot("
"uint256 proposalId,"
"uint8 support"
")"
```

**Comment by k06a** [comment]
This PR is not refactoring but reformatting

**Comment by k06a** [comment]
So WDYT?

**Comment by frangio** [comment]
Hey so I think we're actually not convinced that this formatting looks better. Personally I find the one-line version easier to read, and I think it could come in handy to be able to copy-paste it into JavaScript where the multiline string wouldn't be accepted. Sorry!

**Pull request closed without merging**
