### PR TITLE
ERC20: Prevent transfer to the token contract

### PR DESCRIPTION
**Pull request by dmihal**
There's been a bit of discussion on Twitter today about preventing token transfers to the token contract, after a user lost about $35k worth of YFI.

https://twitter.com/dmihal/status/1293128845994995713
https://twitter.com/nanexcool/status/1293224689146486787

I threw together this PR to open the discussion on blocking transfers to the token contract.

### CODE REVIEW

**Comment by tinchoabbate** [comment]
Isn't this too opinionated ? Why enforce it at the ERC20 contract level when anyone inheriting from ERC20 could just do:

~~~solidity
contract Token is ERC20 {
    constructor() public ERC20("Token", "Token") {}
    function _transfer(address sender, address recipient, uint256 amount) internal override {
	    
	require(recipient != address(this), "ERC20: transfer to the token contract");
		
	super._transfer(sender, recipient, amount);
   }
}
~~~

and programmatically prevent the user error you mention ?

Today contracts inheriting from ERC20 might be actually using deposited tokens in the same token contract for other additional features, and this proposed change would break them.

**Comment by dmihal** [comment]
@tinchoabbate 

Quoting @frangio from another thread

> OpenZeppelin contracts are opinionated precisely because we don't want the burden of making these decisions to be on the developers. If one of our decisions turns out to be a bad one, we don't want it to be in the library at all, not even as an opt-in thing.

https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1493#issuecomment-511084760

**Comment by julianmrodri** [comment]
I think this was before the latest release in which it was decided by OZ to keep the `ERC20` contract as unopinionated as possible, and use the [preset contracts](https://docs.openzeppelin.com/contracts/3.x/api/presets) for opinionated, ready-to deploy implementations. 

We actually added a note in the `README.md`, you can check it [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/README.adoc).

IMHO this is too restrictive and opinionated to include it in the base standard contract. It is also as mentioned a breaking change for existing implementations.

**Comment by frangio** [comment]
Thank you for the suggestion @dmihal.

I agree with @tinchoabbate on this one. Since there could be legitimate use cases for the token contract holding balance, this is a decision that we can't make for the developer.

**Pull request closed without merging**
