### PR TITLE
ERC1155 feature pending tasks

### PR DESCRIPTION
**Pull request by frangio**
This PR tracks the tasks pending to merge `feature-erc1155`, introduced in #1803.

- [ ] Improve extensibility of ERC1155 (#2003)
- [x] Port to Solidity v0.6
- [ ] Re-review the code, mostly for security issues.
- [ ] Add more tests, increase test coverage.
- [ ] Compare with [Augur's implementation](https://github.com/AugurProject/augur/blob/master/packages/augur-core/source/contracts/libraries/token/ERC1155.sol).
- [ ] Review URI support. (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2029)

More tasks may come out of the review.

### CODE REVIEW

**Comment by frangio** [comment]
From @KaiRo-at in #1803:

>Another thing I just noticed is that this PR contains a URI() event in the interface, but nothing using it or anything else related to URIs, so either the event should be removed or the implementation using it some way. Though actually, this may be a bug in the ERC itself, as that even should belong to the "interface ERC1155Metadata_URI" definition in there, I guess... See https://github.com/ethereum/EIPs/issues/1155#issuecomment-565442942

**Comment by KaiRo-at** [comment]
FWIW, I have a very simple catch-all implementation of the metadata URI interface in https://github.com/KaiRo-at/openzeppelin-contracts/commit/859f6e72f78e2f0e18ca06db1678bd3cd4dd728f (a second should probably follow that allows a different URI per id, the catch-all solution is for using the {id} placeholder in the URI), should this go into this PR or its own?

**Comment by frangio** [comment]
@KaiRo-at Please submit in its own PR to the `feature-erc1155` branch. I think we should stick to the catch all URI only, at least for now.

**Comment by KaiRo-at** [comment]
Thanks, created https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2029 but tests are still missing.

**Comment by andresbach** [comment]
Added some minor changes to the test in the PR #2107 (`feature-erc1155-tests` branch)

In the `ERC1155.behavior.js` tests it may be useful to refactor more parts of the functionalities, as it was done with `transferWasSuccessful` and `batchTransferWasSuccessful`. It would be helpful to check the `ERC777.behavior.js` tests for that.

Also, there is a warning telling that `expectEvent.inLogs()` has been deprecated in favor of `expectEvent()`. It should be changed to the newer method.

**Comment by nventuro** [comment]
Working on the different ERC1155 PRs is becoming a bit of a mess, which I think we can simplify by merging current work into `master` and then having PRs target that, as with all other features. 

This may be entirely avoidable and our fault for not properly handling release branches, but since v3.1 is expected to include ERC1155 anyway I don't think merging now will be a problem.

I created https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2230 to replace this PR as the place to track progress.

**Pull request merged**
