### PR TITLE
Initial proposal for ERC2135 and Ticket721 Draft.

### PR DESCRIPTION
**Pull request by xinbenlv**
Hi Open Zeppelin Community, I'd like to add the [ERC2135](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2135.md) and one of its reference implementation to Open Zeppelin repository from https://github.com/xinbenlv/eip-2135/tree/master/impl.

Presubmit CheckList
  - [X] reviewed the OpenZeppelin Contributor Guidelines
    (https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/CONTRIBUTING.md),
  - [X] added tests where applicable to test new functionality,

  - [X] made sure that your contracts are well-documented,
  - [X] run the Solidity linter (`npm run lint:sol`) and fixed any issues,
  - [X] run the JS linter and fixed any issues (`npm run lint:fix`), and
  - [ ] updated the changelog, if applicable. 

Note: I don't know how to **update the changelog** or whether it applies - @xinbenlv

### CODE REVIEW

**Comment by xinbenlv** [comment]
Give the newly added contract coverage is 100% https://coveralls.io/jobs/51165007, I believe the coveralls failure is a false positive.

**Comment by xinbenlv** [comment]
Can anyone kindly help conduct the first review?

**Comment by nventuro** [comment]
Hello @xinbenlv, thanks for contributing to OpenZeppelin! I'm sorry we took so long to review this.

When adding new features (specially new standard interfaces) we usually look for potential use cases that call for them, or demand from the community. Could you share a bit more about projects you're working on where this need came up? 

I can see how burning tokens might be useful (which is why we provide `_burn`), but am unsure as to whether a full-fledged standard interface for doing so is the way to go.

**Comment by xinbenlv** [comment]
Hi @nventuro yes, thanks for a review and suggestion.

Allow me to defend the necessity of the ERC and an standard implementation. I am open to be convinced too.

I think it make sense to have a `burn` or `consume` like ERC to standardize this behavior. The fact that our OpenZapellin version implementation of ERC20 and ERC721 both have found the need of implementing a `burn` function speaks for a need.  This address the "need/use-case" question of a function

And the next question whether it needs a ( full fledge) ERC to help standardize such behavior.
I believe if this is something potentially have many usage, it's better to have a standard so people of different implementation or dapps can interoperate.
 
If the only concern is that is too *trivial*, I would compare it with [ERC-173 Ownership](http://eips.ethereum.org/EIPS/eip-173) which is also very simple. The value of a standard has only a few very trivial methods, but it help people agree to how an ownership is defined and interpreted and how to events are defined is valuable and being standardized is better than not standardized.

Oh actually, you remind me, that for backward compatibility purpose, whether we should rename the ERC-2135 main function `consume` to `burn`, I would like to have your advice.

Thank you!

**Comment by xinbenlv** [comment]
Friendly ping for another round of review / response from reviewers

**Comment by xinbenlv** [comment]
Friendly ping again~

**Comment by frangio** [comment]
I think there is value in stuff like ERC173 and the ERC2135 proposed in this PR. However, IMO it would be best for the ERC to standardize the behavior and names that are already in use, instead of introducing new ones. So I would go for `burn` instead of `consume`, etcetera.

**Comment by frangio** [comment]
I don't really understand the role of `Ticket721` in this. Would you mind explaining?

**Comment by xinbenlv** [comment]
@nventuro, @frangio agree, compatibility is probably the most important when it comes to adoptions. I lean towards using "burn" as well now.

**Comment by frangio** [comment]
Yes, I think I understand. I was asking to understand whether it's something that should be included in the OpenZeppelin Contracts or if it's more like a special-purpose example application. I'm leaning towards the second.

**Comment by xinbenlv** [comment]
@frangio thanks for clarifying. I humbly argue that it is the latter case: it is more of a general case possible being referenced / used by many applications as part of their set of contracts.

**Comment by xinbenlv** [comment]
Hah, thank you Stalebot. I am working on communicating the preferred interface and waiting for community members input to further revise

**Comment by xinbenlv** [comment]
It's still waiting for review.

**Comment by xinbenlv** [comment]
Actually, hold on, I will update the interface to reflect another conversation's suggestion

**Comment by frangio** [comment]
We've decided not to merge this because there doesn't seem to be a lot of interest in the ERC, and moreover it's still a Draft, which we usually don't include because the API may change and we need to keep a stable API.

Sorry for taking a while to come to a definitive answer. Thank you @xinbenlv!

**Pull request closed without merging**
