### PR TITLE
Fix governance tutorial contract

### LINKED ISSUE #3947: Governor docs example fails to compile
# Overview
Using the Governor [example](https://github.com/openzeppelin/openzeppelin-contracts/blob/d59306bd06a241083841c2e4a39db08e1f3722cc/docs/modules/ROOT/pages/governance.adoc#L144-L245 ) in the docs fails to compile due to an incorrect override in line 188.

## **💻 Environment**

hardhat `2.12.6`
solidity `^0.8.2`
ubuntu `22.04.1 LTS`

## **📝 Details**

In [line 188](https://github.com/openzeppelin/openzeppelin-contracts/blob/d59306bd06a241083841c2e4a39db08e1f3722cc/docs/modules/ROOT/pages/governance.adoc#L188) of the Governor docs, the `getVotes` function overrides `GovernorVotes` rather than `Governor` which causes compilation of the file to fail.

## **🔢 Code to reproduce bug**

1. Create a new file named `MyGovernor.sol` in the `contracts/` folder of this repo and copy the contents of lines 145-243 below into the file.
https://github.com/openzeppelin/openzeppelin-contracts/blob/d59306bd06a241083841c2e4a39db08e1f3722cc/docs/modules/ROOT/pages/governance.adoc#L145-L243
2. Run `npm install` or `npm run compile` to compile the contracts

### PR DESCRIPTION
**Pull request by omurovec**
Fixes #3947 

Fixes typo in governance docs which causes example to fail to compile.

#### PR Checklist

- [ ] Tests
- [x] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @omurovec, and thank you for raising this.

AFAIK, this should probably not be overridden at all. I'll see if that can't be cleaned up even further

**Comment by omurovec** [comment]
Great! Was also planning to create a duplicate issue in the upgradeable repo since I believe it has the same issue.
@Amxx

**Comment by frangio** [comment]
Pretty sure this was broken due to the changes to `getVotes` in 4.6.0.

I noticed that the imports were wrong as well so included that in this PR.

**Review by frangio — DISMISSED** [review]

**Review by frangio — APPROVED** [review]
Interesting that seems to compile as well. Opened https://github.com/OpenZeppelin/contracts-wizard/issues/218.

**Pull request merged**
