### PR TITLE
Updated ERC1155 tests

### PR DESCRIPTION
**Pull request by andresbach**
Fixes #

ERC1155 tests has been updated.
This PR is related to the mentioned tasks in PR #2014

### CODE REVIEW

**Comment by nventuro** [comment]
Definitely relevant! We'll start ramping up work on ERC1155 next week.

**Comment by nventuro** [comment]
Oof, I completely missed this PR. We should review it once #2267 is in.

**Comment by frangio** [comment]
@nventuro What's the status of this PR?

**Comment by nventuro** [comment]
I'd like to wait until https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2291 is in, so we can use it to guide the test development process in case we're missing coverage.

**Comment by frangio** [comment]
Waiting for #2291.

**Pull request merged**
