### PR TITLE
Modify ReentrancyGuard to reduce contract size

### PR DESCRIPTION
**Pull request by abhi3700**
Refer issue #3514 

I wrapped the code present in function `modifier` with 2 functions (private) outside & just call the function(s) inside the modifier.

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @abhi3700 and thank you for this PR.

I think we would want better naming. Maybe something like `_nonReentrantBefore`, `_nonReentrantAfter` ?

**Comment by abhi3700** [comment]
Yeah great!

**Review by frangio — CHANGES_REQUESTED** [review]
@abhi3700 Can you implement the changes suggested by @Amxx?

**Comment by frangio** [comment]
Did you measure the additional runtime cost?

**Comment by abhi3700** [comment]
> @abhi3700 Can you implement the changes suggested by @Amxx?

Done! ✅

**Comment by abhi3700** [comment]
> Did you measure the additional runtime cost?

In my repo, 
the compile result with standard "ReentrancyGuard" is `9.72s`
image

And the compile result with standard "ReentrancyGuard" is `9.29s`
image

The compile time differs because of the machine running concurrent applications at this time.

So, it can be seen that the contract size is highly reduced by `0.308 KB`

**Review by frangio — APPROVED** [review]
Thanks!

**Pull request merged**
