### PR TITLE
Reorder state changes and event emission for consistency

### PR DESCRIPTION
**Pull request by Amxx**

### CODE REVIEW

**Comment by frangio** [comment]
On second thought about this, I think we should emit events after state changes... It's what we do everywhere else already.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/23869e5b2a7c6b9c3e27dee4289615b8cf50e36b/contracts/token/ERC20/ERC20.sol#L220-L222

**Comment by Amxx** [comment]
In transferOwnership (and other places where the event contains the "old value") we emit the event before doing the state change. This is so the event can read the old state from storage without having to assign a temporary variable.

This is why I followed this logic ... but its true that in tokens we emit events after ...

**Comment by Amxx** [comment]
I have the feeling that our logic is "Emit the event after changing the state, unless the event needs knowledge of the previous state" 

Maybe we should keep doing that.

**Comment by frangio** [comment]
Sorry did that last edit before seeing these comments thinking we had agreed.

I get that it's technically consistent if we establish this convention you just mentioned, but it's not immediately apparent that the convention is "do this unless we need to do this other thing", and I don't see an issue in defining a local variable.

**Review by petross8901 — APPROVED** [review]

**Review by frangio — APPROVED** [review]

**Pull request merged**
