### PR TITLE
Fix arbitrum L1 to L2 crosschain call detection

### PR DESCRIPTION
**Pull request by Amxx**
#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Review by frangio — APPROVED** [review]
Looks good to me.

**Comment by frangio** [comment]
Updated the changelog, assuming we will release this as 4.7.2.

**Review by frangio — APPROVED** [review]

**Comment by Amxx** [comment]
Do we need a changelog entry / notice ?

**Comment by frangio** [comment]
Personally I think the changelog entry I wrote down is ok. For a larger warning we will have an advisory.

**Pull request merged**
