### PR TITLE
Optimize Strings.equal

### PR DESCRIPTION
**Pull request by CodeSandwich**
Fixes #NONE

It's a really small optimization avoiding hashing strings when they're obviously different.

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [x] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by frangio** [comment]
Thanks for the clear title. :stuck_out_tongue: 

This is definitely good, we just need a changeset. Can you add it or let me know if I should do that for you.

**Comment by CodeSandwich** [comment]
I've added the changeset. Sorry for not doing it before, this PR seemed too small to litter the changelog with it :shrug:

**Review by Amxx — APPROVED** [review]

**Comment by Amxx** [comment]
> BTW you've added this PR to the 5.0 milestone, does it mean that it won't be available in 4.9.1 and 4.10 if such versions ever exist? I'm not a project maintainer, but it seems strange, it's not a breaking change or even a new feature.

- If there ever is a 4.9.1, it will be about bug fixes, not about new features and optimizations.
- We don't plan a 4.10.
- From now on, all features and optimizations are indeed planned to be in 5.0

**Review by Amxx — APPROVED** [review]

**Review by ernestognw — APPROVED** [review]
Nicee, thanks!

**Pull request merged**
