### PR TITLE
fix: detailed explanation of what a function does

### PR DESCRIPTION
**Pull request by Chiadikaobixo**
Fixes #???? 

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [x] Changelog entry

### CODE REVIEW

**Comment by frangio** [comment]
@Chiadikaobixo Are you a human? Otherwise we will block the account from further contributions due to spam.

**Comment by Chiadikaobixo** [comment]
Yes I’m human. I’m finding it difficult for my changelog to pass while
creating a pull request.

**Comment by frangio** [comment]
The changelog won't pass unless you modify the changelog, but you don't need to do that for every PR. This change you're trying to make would not need a changelog. That said, I am not sure this change would be accepted.

**Comment by Chiadikaobixo** [comment]
Thanks very much, this is my first attempt on opensource and I am glad to know this. I look forward to contributing soon.

**Pull request closed without merging**
