### PR TITLE
Fix function state mutability warning

### PR DESCRIPTION
**Pull request by zemse**
Hi @frangio, on upgrading to `3.2.0-solc-0.7` release, I noticed that the commit from the PR #2327 wasn't included. But it's there in `solc-0.7` branch but seems it got missed out in this release branch.

I understand that this is a release branch so any more changes are not added to it, but can you merge this PR in the next release branch if it were to be created from this branch instead of `solc-0.7`?

### CODE REVIEW

**Comment by fvictorio** [comment]
I think you meant to tag @frangio? :sweat_smile:

**Comment by zemse** [comment]
Oh I'm sorry for the spam! I meant to tag him but didn't notice that you got tagged

**Comment by frangio** [comment]
@zemse Oh, this was my bad. I built the release based on the branch `release-3.1-solc-0.7` instead of `solc-0.7`. It should've been the latter. I didn't have this workflow well polished. I'm going to publish a new release with the branch merged in.

**Comment by frangio** [comment]
Fixed and released as `3.2.1-solc-0.7`.

**Comment by zemse** [comment]
Thank you!

**Pull request closed without merging**
