### PR TITLE
Fix Typo in Math.sol

### PR DESCRIPTION
**Pull request by dimitriospapathanasiou**
Fixes minor typo in Math.sol documentation

- [ ] Tests
- [x] Documentation
- [ ] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by ernestognw** [comment]
Hi, this doesn't seem to be a typo.

> Operation will be marked as failed

vs 

> Operation will be marked has failed

I'm closing

**Comment by dimitriospapathanasiou** [comment]
Hi, I corrected it to "as failed" as the word -has- doesn't seem to be in alignment with the sentence meaning.

Nothing of importance though, I just bumped into this while studying the file.

Thanks for your time.

**Comment by ernestognw** [comment]
> Hi, I corrected it to "as failed" as the word -has- doesn't seem to be in alignment with the sentence meaning.
> 
> Nothing of importance though, I just bumped into this while studying the file.
> 
> Thanks for your time.

Thanks for bumping! I reviewed too fast and concluded it was the opposite (switching `as` to `has`)
We get a couple of these PRs that are spam most of the times, sorry 😅

**Review by ernestognw — APPROVED** [review]

**Comment by dimitriospapathanasiou** [comment]
Thank you for reassessing it!

**Pull request merged**
