### PR TITLE
ERC998 addition

### PR DESCRIPTION
**Pull request by 3scava1i3r**
Opened Issue #3062 for addition of ERC998
Fixes #???? 
Issue number #3062 

#### PR Checklist
This PR right now only consist of TopDown Composable code for ERC998

- [ ] Tests
- [ ] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @3scava1i3r 

We usually want to discuss new features like this in issues (like the one you created) before we start putting work on an actual implementation.

From what I can see, you already did quite a lot of work, but what you did doesn't really meet the design pattern we go for. Some of you overrides are erroneous (not calling super in `supportsInterface`). You also re-implement a lot of things that are already available as tools (duplicate of the SafeMath lib, duplicate of `isContracts`...)

I would strongly advise you don't put effort on that until the issue is properly discussed. I don't want you to get frustrated if it turns out a PR you spent times on ends up not getting merged.

**Comment by 3scava1i3r** [comment]
I understand the same, will engage in more discussion on the same

**Comment by TrejGun** [comment]
Hey @Amxx 

as I said [here](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3062#issuecomment-1017520715) this standard is complicated and heavy. It is probably makes sense to implement good [EIP-2535](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2793) support in OZ first and then I will be glad to share the fresh and compatible code of ERC998 with extensions

**Comment by frangio** [comment]
Closing for reasons explained in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3062#issuecomment-1033177430.

**Comment by 3scava1i3r** [comment]
@TrejGun i can help out in 2535 i suppose it is the diamond standard,then help out with the newly made ERC998

**Pull request closed without merging**
