### PR TITLE
Add .circleci/config.yml

### PR DESCRIPTION
**Pull request by puchaw**
Fixes #

### CODE REVIEW

**Comment by KaiRo-at** [comment]
I smell something weird going on here. My guess would be that this user may be trying something sinister.

**Comment by abcoathup** [comment]
Closing as appears to be in error (potentially spam)

**Comment by KaiRo-at** [comment]
@abcoathup thanks for that. This user also made some confusing comments in #2174 (that's what led me to dig up what else this user has been doing and find this).

**Comment by frangio** [comment]
I've blocked the user from the OpenZeppelin organization.

**Pull request closed without merging**
