### PR TITLE
Decrease CREATE2 address computation gas usage from 623 to 539

### PR DESCRIPTION
**Pull request by k06a**
Small fix

### CODE REVIEW

**Comment by frangio** [comment]
Does the `address` cast to the necessary masking?

**Comment by k06a** [comment]
@frangio, yep, sure.

**Comment by nventuro** [comment]
I run a small test to confirm this:

```solidity
contract TestA {
    function foo(uint256 a) public pure returns (uint256) {
        address b = address(a);
        return uint256(b);
    }
}
```

When called with `115792089237316195423570985008687907853269984665640564039457584007913129639935` (2^255 - 1), it returns `1461501637330902918203684832716283019655932542975` (2^160 - 1).

**Comment by k06a** [comment]
@frangio 👌

**Pull request merged**
