### PR TITLE
Making "uint" explicit as "uint256" within SignatureBouncerMock.sol

### PR DESCRIPTION
**Pull request by Luiserebii**
This is a really minor change I wanted to suggest. I was looking over the repo, and noticed that this contract has an implicit type via usage of `uint`, and thought that changing it to `uint256` would be safe.

I ran the tests, and there are 27 that are failing which are unrelated to this change, I think. To be sure, I cloned a separate copy and ran the tests, and got the same results, so I imagine it is ok to make a PR?

Thanks!
Luiserebii~

### CODE REVIEW

**Comment by Skyge** [comment]
Explicit is always better than implicit.

**Comment by Skyge** [comment]
@Luiserebii There is an Irrelevant typo in the file: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L179, could you please correct it at the same time? it should be 
```
/** (< === here)
 *
 */
```
I found it just now, and I do not want to make a separate pr just for fixing it in one changing line.

**Comment by Skyge** [comment]
Maybe you can run `npm run lint`, I am not sure.

**Comment by Luiserebii** [comment]
Hey @Skyge! 

Just made the addition, no worries! I think since it is a really minor change, it should be ok to also include in this PR :smiley:

**Comment by Skyge** [comment]
Okay.

**Comment by nventuro** [comment]
As mentioned in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1879, I'm closing this due to `SignatureBouncer` being removed in v2.4.

@Luiserebii I'm sorry to see your work go unmerged :( Thanks for contributing though!

**Pull request closed without merging**
