### PR TITLE
Fix visibility in ERC721._checkOnERC721Received documentation

### PR DESCRIPTION
**Pull request by Hicham010**
This pull request converts the `_checkOnERC721Received` from a private function to an override-able internal function. This is according to the documentation on the function.

- [ ] Tests
- [ ] Documentation
- [ ] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by frangio** [comment]
Thanks @Hicham010. I think it's the documentation that is wrong here. Are you suggesting this change because you noticed the discrepancy or because you have a use case that requires overriding this function?

**Comment by Hicham010** [comment]
> Thanks @Hicham010. I think it's the documentation that is wrong here. Are you suggesting this change because you noticed the discrepancy or because you have a use case that requires overriding this function?

I noticed the discrepancy while reading the contract. I currently have no use case.

**Comment by ernestognw** [comment]
I agree the documentation is what's not appropriate here. I don't see why someone would change this function and doing so would make the contract non compliant so I'd keep it private unless there's a concrete use case.

Can we instead update the docs removing the "Internal" mention @Hicham010?

**Comment by Hicham010** [comment]
> I agree the documentation is what's not appropriate here. I don't see why someone would change this function and doing so would make the contract non compliant so I'd keep it private unless there's a concrete use case.
> 
> Can we instead update the docs removing the "Internal" mention @Hicham010?

Updated the docs.

**Review by frangio — APPROVED** [review]

**Review by Amxx — APPROVED** [review]

**Pull request merged**
