### PR TITLE
Fix natspec comment missing *

### PR DESCRIPTION
**Pull request by Amxx**

### CODE REVIEW

**Comment by ericglau** [comment]
Would it make sense to add a custom Solidity linting rule for this?

**Comment by Amxx** [comment]
> Would it make sense to add a custom Solidity linting rule for this?

yes!

If there is a `@dev` or similar tag in a comment that is not `///` or `/**`, then raise an error.

**Review by ernestognw — APPROVED** [review]

**Comment by ericglau** [comment]
Looks like Solhint doesn't support parsing comments since it's not part of the AST, so the linting suggestion above may be a future consideration.

**Comment by pedrobergamini** [comment]
lol I was looking for a Heap lib and just found this recently merged. Congrats and thanks for your work!

**Pull request merged**
