### PR TITLE
EnumerableMap.AddressToUintMap

### PR DESCRIPTION
**Pull request by Tynukua**
Fixes #???? 

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @Tynukua 

Do you have a specific need for this flavor of EnumerableMap? Are you planning to use it for storing balances?

I think it would be a great addition to this library, but I would go one step further and `addressToBytes32` and `bytes32ToAddress` functions to cleanup all the casting. They could be file-level function, or we could add them to a library (either safecast or something new)

**Comment by fdietze** [comment]
I am also interested in this addition.

My use case would indeed be to store balances.

**Comment by gaspardip** [comment]
Same use case here, surprised it has't been added yet.

**Comment by Amxx** [comment]
I don't think there is any reason not to include that.

The next steps would be to add testing and a Changelog entry.

**Comment by gaspardip** [comment]
> I don't think there is any reason not to include that.
> 
> The next steps would be to add testing and a Changelog entry.

I can do that, should I continue this in another CR?

**Comment by frangio** [comment]
Closing in favor of https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3150.

**Pull request closed without merging**
