### PR TITLE
Draft: Add return values to Counters

### PR DESCRIPTION
**Pull request by k06a**
Idea to improve usability of `Counters`. Let's discuss if it is a good idea.

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @k06a, and thanks for the proposal.

I really like the idea of having `increment` and `decrement` return uint256 value of the counter. On the other hand, I'm not sure about the `incremented` and `decremented`. I think these two might be confusing to some user.

What would you think of moving forward with the return values for increment and decrement first (this could go in the next release), and maybe open an issue to discuss the additional functions.

**Comment by k06a** [comment]
@Amxx so you're ok with these methods returning previous state?

**Comment by Amxx** [comment]
I understand that this would be the lost usefull value to return... but at the same time I'm afraid this might be confusing...

**Comment by frangio** [comment]
Hey @k06a, we discussed this a little more and we think there is too much potential for confusion between `increment` and `incremented`, that we don't think this would be a good idea.

The pricing changes in Berlin also make this a less important optimization.

**Pull request closed without merging**
