### PR TITLE
Use shorter syntax for Escrow addition

### LINKED ISSUE #2659: Cosmetic change in Escrow.sol
**🧐 Motivation**

Modify Escrow.sol to incorporate short-hand add notation

**📝 Details**

Current => a = a + 1
Updated => a += 1

### PR DESCRIPTION
**Pull request by Manik-Jain**
Using short hand notation for add operation

Fixes #2659 

#### PR Checklist

- [x] Tests
- [x] Documentation
- [x] Changelog entry

### CODE REVIEW

**Comment by Manik-Jain** [comment]
Hi @frangio 

Could this be reviewed?

**Comment by frangio** [comment]
@Manik-Jain Can you make this PR only about the `+=` operator, and if you think we're missing these require statements create an issue to discuss it separately.

**Comment by Manik-Jain** [comment]
Change done. Yes, I missed to create the Issue for this change.
I've created the issue under listing : https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2659

Thanks

**Review by frangio — APPROVED** [review]
Thank you!

**Pull request merged**
