### PR TITLE
Disable Travis in favor of Circle

### PR DESCRIPTION
**Pull request by frangio**

### CODE REVIEW

**Comment by frangio** [comment]
I'm putting this on hold because I haven't figured out how to set up the Coveralls status check with CircleCI without potentially exposing the Coveralls token to anyone who opens a PR.

CircleCI [Contexts](https://circleci.com/docs/2.0/contexts/#creating-and-using-a-context) may be a way to set this up.

We could also consider Codecov since they seem to have a preset for Circle.

**Comment by frangio** [comment]
Migrating to Codecov which doesn't need the token.

**Comment by xinbenlv** [comment]
Cool, great to know~

**Comment by xinbenlv** [comment]
And we completely remove Travis? cool. But... I thought we will let it run in parallel for a while until CircleCI proofed stable

**Comment by frangio** [comment]
I've been testing it quite a lot today and it's working great.

**Comment by xinbenlv** [comment]
Awesome. Sure

**Pull request merged**
