### PR TITLE
Improvement. Make sure the new owner isn't the old owner, which will reduce misoperations.

### PR DESCRIPTION
**Pull request by FrankLiu007**
Fixes #???? 

check if the new owner is the old owner before transferOwnership which will reduce misoperations.

> before
```
    function _transferOwnership(address newOwner) internal virtual {
        address oldOwner = _owner;
        _owner = newOwner;
        emit OwnershipTransferred(oldOwner, newOwner);
    }
```
> after
```
    function _transferOwnership(address newOwner) internal virtual {
        require(_owner!=newOwner, "Ownable: the newOwner is the same with the old owner");
        address oldOwner = _owner;
        _owner = newOwner;
        emit OwnershipTransferred(oldOwner, newOwner);
    }
```

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by Amxx** [comment]
Hello @FrankLiu007 

We don't have any reason to prevent transferring to the current owner. Will it can be debated why someone would do that, its a valid no-op that doesn't need reverting.

Changing that behavior might break some usecases/applications. That is something we will want to avoid.

Why do you think transferring to the current owner is problematic and should cause a revert?

**Comment by Amxx** [comment]
If you want to add this behavior to a contract of your own, you can do it like this


```solidity
function _transferOwnership(address newOwner) internal virtual override {
    require(owner() != newOwner, "Ownable: the newOwner is the same with the old owner");
    super._transferOwnership(newOwner);
}
```

**Comment by FrankLiu007** [comment]
@Amxx Hello. No one want to transferring ownership to the current owner. If this happens, it means that something unwanted happened. Reverting the transcation gives the developer a seconder chance to review the code. Security should always be the top consideration.

**Comment by Amxx** [comment]
> @Amxx Hello. No one want to transferring ownership to the current owner. If this happens, it means that something unwanted (maybe bad) happened.

You may not want it, but saying no-one want it is an exaggeration. If you think of tokens like erc20 and erc721, it is valid to

- transfer token to yourself
- transfer 0 tokens.

It's even valid to transfer 0 tokens to yourself!

These are all valid no-op that will happen (particularly with contract composition). We don't want to block these usecases for everyone. We also don't want to add opinionated behavior that are not explicit in the ERCs.

Still, if you want your contracts to not allow such a transfer, that is your choice to make, and it's easy for you to add that.

**Comment by FrankLiu007** [comment]
@Amxx I think you are right. Sorry for the inconveniency.

**Pull request closed without merging**
