### PR TITLE
 Reorganize the repo structure

### PR DESCRIPTION
**Pull request by Amxx**
Fixes https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2527. See the issue for more details.

#### PR Checklist

- [x] Tests
- [x] Documentation
- [x] Changelog entry

### CODE REVIEW

**Comment by frangio** [comment]
Notes from offline conversation:

- Interfaces such as a `IERC777Sender` should go at the top level ERC777 directory.
- Rename `proxy/upgradeable` to `proxy/transparent` and move `UpgradeableProxy` to `proxy`.
- Maybe `TimelockController` should go in its own directory of standalone contracts. Does this belong in `utils`? This category could also contain `TokenTimelock`, `PaymentSplitter`.
- A new `enumerable` directory.
- Try to move `mocks` directory somewhere less visible.

**Comment by Amxx** [comment]
What about moving the `mocks/*` into `test/mocks/*` ?

**Review by frangio — DISMISSED** [review]

**Comment by frangio** [comment]
Will merge on Monday!

**Review by frangio — APPROVED** [review]

**Comment by Rsed19901** [comment]
> Fixes https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2527. See the issue for more details.
> 
> #### PR Checklist
> 
> - [x] Tests
> - [x] Documentation
> - [x] Changelog entry
>

**Pull request merged**
