### PR TITLE
Procedurally generate Arrays.sol

### PR DESCRIPTION
**Pull request by RenanSouza2**
This PR creates scripts to generate the Arrays.sol file,

It also includes tests for unsafeMemoryAccess functions

#### PR Checklist

- [X] Tests
- [ ] Documentation
- [ ] Changeset entry (run `npx changeset add`)

### CODE REVIEW

**Comment by RenanSouza2** [comment]
Hey, 

Are you interested in adding a function for bytes32 memory array?

There are lots of simplifications that can be done if there are the same functions for both array and storage

**Comment by Amxx** [comment]
Hello @RenanSouza2 

We have multiple PR targetting Array.sol. #4846, #4842. I'm not sure we need to generate this file procedurally. I'd delay that decision until after the above PR are processed.

**Review by ernestognw — COMMENTED** [review]
I made a few adjustments after the other Arrays PRs got merged.
Right now it looks good to me but we might want to discuss how the generation script is ordered.

WDYT @Amxx ?

**Review by Amxx — APPROVED** [review]

**Comment by ernestognw** [comment]
I agree with minimizing the diff. So LGTM as well.
However, I do think the previous ordering is better when reading the generation script. No need to update it now since I don't think the ordering is strictly important, but wanted to point it out.

**Pull request merged**
