### PR TITLE
Port ERC 1155 branch to Solidity 0.6 (and current master)

### PR DESCRIPTION
**Pull request by KaiRo-at**
This includes the previous work for #1803 my PR #2029 and also makes all the ERC1155 work compile with Solidity 0.6, rebased against current master.

If it's not the right way to submit a PR against master but I should instead do this in a different way, please let me know.

### CODE REVIEW

**Comment by nventuro** [comment]
Hm, I tried changing the target branch to `feature-erc1155`, but that made the PR messier. Could you try rebasing your branch on top of that one, so that we get a clean diff? 

Actually, if you could isolate commit https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2130/commits/94795185c86a836bbe07c282897d7fcae0818888 that'd be even better, to keep the PR focused. Thanks!

**Comment by KaiRo-at** [comment]
> Hm, I tried changing the target branch to `feature-erc1155`, but that made the PR messier. Could you try rebasing your branch on top of that one, so that we get a clean diff?

If the branch was rebased on current master, then this probably would make more sense - unfortunately, without that, I can't even try to run tests on the result...

**Comment by nventuro** [comment]
I see what you mean, yes. I just merged master on top of the feature branch - you should be able now to extract the commit with the language version port, landing us on a cleaner PR.

Note that the feature branch will be temporarily broken until we port it to 0.6.

**Comment by KaiRo-at** [comment]
OK, I removed all the pieces related to #1803 / #2029 from this and rebased this on top of the upstream feature-erc1155 branch, so this is only the 0.6 work (and the constructor stuff, but if you want, I can take that out as well and move it into work on #2003 or so.

**Comment by KaiRo-at** [comment]
AFAIK review is blocking this, hope that will come soon now that 3.0 is out.

**Pull request merged**
