### PR TITLE
Introduce ERC1155 totalSupply() and exists() functions

### PR DESCRIPTION
**Pull request by Amxx**
Followup to #2185

#### PR Checklist
- [x] Tests
- [x] Documentation
- [x] Changelog entry

### CODE REVIEW

**Comment by frangio** [comment]
Do we know if there is precedent for these `totalSupply` and `exists` functions? I'd like to check that we aren't making them incompatible with something that's already out there.

**Comment by frangio** [comment]
The code in this PR needs to remove SafeMath.

**Comment by Amxx** [comment]
> The code in this PR needs to remove SafeMath.

done.

**Comment by Amxx** [comment]
> Do we know if there is precedent for these `totalSupply` and `exists` functions? I'd like to check that we aren't making them incompatible with something that's already out there.

Not 100% sure. I've discussed usecase where 1155 could be used for voting, and total supply was useful ... but that is everything

**Comment by frangio** [comment]
`totalSupply` in OpenSea: https://github.com/ProjectOpenSea/opensea-erc1155/blob/baa203757e33fc41e5465e3c2e6b0de82391c7fd/contracts/ERC1155Tradable.sol#L73-L77

They also have an internal `_exists` function which has different semantics than the `exists` in this PR, but it could be overriden or extended through inheritance.

**Review by frangio — APPROVED** [review]

**Comment by conorbros** [comment]
When will these changes be released?

**Comment by frangio** [comment]
We're aiming for a release candidate on June 3rd.

**Comment by Parth2404** [comment]
Is this release yet or not??

**Comment by Amxx** [comment]
> Is this release yet or not??

Its been released in 4.2.0 (2021-06-30)

**Pull request merged**
