### PR TITLE
WIP - Have Escrow forward all gas on withdraw.

### PR DESCRIPTION
**Pull request by nventuro**
Fixes https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1668.

I'm not a fan of the library name, but this is the general idea. There's still ongoing discussion regarding whether or not this is actually a good idea, so tagging as WIP.

### CODE REVIEW

**Comment by nventuro** [comment]
This is being paused for now, see [this comment](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1668#issuecomment-484234293) in the related issue.

**Comment by nventuro** [comment]
Given the recent discussions in the community around [EIP 1884](https://eips.ethereum.org/EIPS/eip-1884), it may make sense to review this and other usages of `transfer`. However, these should probably be considered breaking changes, since they allow for interactions that weren't possible before, and may introduce reentrancy risks.

**Comment by nventuro** [comment]
This should probably be implemented in terms of https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1962 (which is pretty much the same as this PR).

I'm still not sure though regarding this breaking the API or not. Perharps we should deprecate `PullPayment` and create a `PullPayment2`?

**Comment by frangio** [comment]
After some discussion we feel it would be irresponsible to change the behavior of `PullPayment` in this way, and we think the best way forward is to deprecate the current `withdraw` functions and add alternatives which do not limit gas.

**Comment by nventuro** [comment]
Superceded by 1976

**Pull request closed without merging**
