### PR TITLE
Optimize ceilDiv() unchecked math

### PR DESCRIPTION
**Pull request by k06a**
Code is equivalent in terms of math overflow safety

### CODE REVIEW

**Review by Amxx — APPROVED** [review]
LGTM for 5.1

**Comment by k06a** [comment]
@Amxx what about `4.9.4`? BTW, it's 176 gas cheaper on latest compiler with a default settings.

**Comment by Amxx** [comment]
We are not planing any `4.9.4`.

**Comment by Amxx** [comment]
This was actually fixed in #4553

**Pull request closed without merging**
