### PR TITLE
Use unchecked arithmetic in "_transfer" and "_mint"

### PR DESCRIPTION
**Pull request by paulrberg**
Implements https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3512.

There are no tests to write for this change.

### CODE REVIEW

**Comment by Amxx** [comment]
Thank you @paulrberg  for the PR.

Can you please make sure the linter pass? You can run `npm run lint:fix` to automatically fix it.

**Comment by Amxx** [comment]
Also, It would be great to run the `ERC20.test.js` with `ENABLE_GAS_REPORT=true` to see the difference.

**Review by Amxx — APPROVED** [review]

**Comment by Amxx** [comment]
Could you also use a small changelog entry please?

**Comment by paulrberg** [comment]
Done, ser.

**Comment by frangio** [comment]
I added comments explaining why we can use `unchecked` for these operations.

**Review by frangio — APPROVED** [review]

**Review by Amxx — APPROVED** [review]

**Pull request merged**
