### PR TITLE
Create2 feature pending tasks

### LINKED ISSUE #1644: Add CREATE2 contract factory
As discussed with @cwhinfrey, @jamesyoung and @spalladino, it'd be interesting to include a factory such as [archanova's](https://github.com/archanova/solidity/blob/08f8f6bedc6e71c24758d20219b7d0749d75919d/contracts/contractCreator/ContractCreator.sol) (by @stanislaw-glogowski, which uses CREATE2, making it possible to predict the contract's address) into OpenZeppelin, possibly expanding upon it to cover more use cases.

One aspect in particular I'd like to discuss is constructor arguments: the linked implementation has a fixed bytecode, but it shouldn't be too difficult to come up with a scheme where these initial values are injected.

### PR DESCRIPTION
**Pull request by frangio**
This PR tracks the tasks pending to merge `feature-create2`, introduced in #1744.
Fixes #1644

Pull requests are accepted!

- [x] Consider alternative names that are maybe more descriptive.
- [x] Add a revert reason when the deploy fails.

### CODE REVIEW

**Comment by frangio** [comment]
>  Consider alternative names that are maybe more descriptive.

We're keeping `Create2` with the argument of familiarity: even though it's a bad name, it's the name of the underlying opcode `CREATE2`: developers may already be familiar with it, there is certainly a lot of material about it online, and it will be easier to find this library if the name is `Create2`.

**Comment by frangio** [comment]
Regarding the revert reason, we may have to do something like this in #2018.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6f333625329ec2df208aab834e07d189b8d3448d/contracts/token/ERC721/ERC721.sol#L333-L350

**Comment by AugustoL** [comment]
Going to add the revert reason when deploy fails.

**Comment by nventuro** [comment]
Thanks everyone for your work! :tada:

**Pull request merged**
