### PR TITLE
Draft 1 - logic for ERC721 Votes contract

### PR DESCRIPTION
**Pull request by alderAcres**
- Starting logic for implementing custom weights for individual tokenIds
- Getting, setting, deleting functionality for userTokenBalances mapping
- Comments for future implementations needed and dev remarks for clarity

### CODE REVIEW

**Comment by alderAcres** [comment]
- Modified checkpoints to update weight incrementally
- Deleted inheritance from ERC20-Permit contract
- Modifier cleanup
- Updated commentary on ERC721-Votes contract
- Added the afterTokenTransfer fn to the core ERC721 contract

**Comment by alderAcres** [comment]
- Modified _delegate fn to initialize user token weight (using token balance)
- Comment cleanup

**Comment by alderAcres** [comment]
- Implemented basic structure for ERC721Votes.test file
- Created an ERC721VotesMock, draft-ERC721VotesPermit, and draft-IERCVotes721 (needed for testing)
-General updates/ modifications to code as needed for cleanup

**Comment by frangio** [comment]
Thank you @alderAcres. As we discussed, closing this PR for now. We'll resume work on the feature in the future.

**Pull request closed without merging**
